# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
---
configs:
  cm:
    create: true
    dex.config: |
      connectors:
      - type: ldap
        name: ldap.127.0.0.1.nip.io
        id: ldap
        config:
          # Ldap server address
          host: "slapd.ldap.svc.local"
          insecureNoSSL: true
          insecureSkipVerify: true
          # Variable name stores ldap bindDN in argocd-secret
          bindDN: "$dex.ldap.bindDN" 
          # k -n argocd patch secrets argocd-secret --patch "{\"data\":{\"dex.ldap.bindDN\":\"$(echo cn=admin,dc=acme,dc=local | base64 -b0)\"}}"
          # Variable name stores ldap bind password in argocd-secret
          bindPW: "$dex.ldap.bindPW" 
          # k -n argocd patch secrets argocd-secret --patch "{\"data\":{\"dex.ldap.bindPW\":\"$(echo changeit | base64 -b0)\"}}"
          usernamePrompt: Username
          # # Ldap user search attributes
          # userSearch:
          #   baseDN: "ou=Users,dc=acme,dc=local"
          #   filter: "(objectClass=person)"
          #   username: uid
          #   idAttr: uid
          #   emailAttr: mail
          #   nameAttr: cn
          # # Ldap group search attributes
          # groupSearch:
          #   baseDN: "ou=Groups,dc=acme,dc=local"
          #   filter: "(objectClass=groupOfNames)"
          #   userAttr: DN
          #   groupAttr: member
          #   nameAttr: cn     

rbac:
  create: true
  policy.csv: |
    p, role:none, *, *, */*, deny
    g, Acme Users, role:readonly
    g, Acme Superusers, role:admin


server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - argocd.127.0.0.1.nip.io
      # - &host argocd.127.0.0.1.nip.io
    paths:
      - /
    # tls:
    #   - secretName: argocd-tls-certificate
    #     hosts:
    #       - *host
  metrics: &metrics
    enabled: true
    serviceMonitor:
      enabled: true
dex:
  enabled: true
controller:
  metrics: *metrics
repoServer:
  metrics: *metrics
redis:
  metrics: *metrics