# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
---
configs:
  cm:
    create: true
    dex.config: |
      connectors:
      - type: ldap
        name: slapd
        id: ad
        config:
          # Ldap server address
          host: "slapd"
          insecureNoSSL: true
          insecureSkipVerify: true
          # Variable name stores ldap bindDN in argocd-secret
          bindDN: "cn=service,ou=Users,dc=acme,dc=local"
          # Variable name stores ldap bind password in argocd-secret
          bindPW: "changeit"
          usernamePrompt: Username
          # Ldap user search attributes
          userSearch:
            baseDN: "ou=users,dc=acme,dc=local"
            filter: ""
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: displayName
          # Ldap group search attributes
          groupSearch:
            baseDN: "ou=groups,dc=acme,dc=local"
            filter: "(objectClass=groupOfNames)"
            userAttr: DN
            groupAttr: member
            nameAttr: cn     

rbac:
  create: true
  policy.csv: |
    p, role:none, *, *, */*, deny
    g, Acme Users, role:readonly
    g, Acme Superusers, role:admin


server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - argocd.homelab.com
      # - &host argocd.homelab.com
    paths:
      - /
    # tls:
    #   - secretName: argocd-tls-certificate
    #     hosts:
    #       - *host
  metrics: &metrics
    enabled: true
    serviceMonitor:
      enabled: true
dex:
  enabled: true
controller:
  metrics: *metrics
repoServer:
  metrics: *metrics
redis:
  metrics: *metrics