# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
---
grafana: # https://www.infracloud.io/blogs/tracing-grafana-tempo-jaeger/
  enabled: true
  adminPassword: password
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    labels: {}
    hosts: 
      - grafana.127.0.0.1.nip.io
    paths: 
      - /
    # pathType: ImplementationSpecific
  # additionalDataSources:
  # - name: loki
  #   type: loki
  #   uid: my-loki
  #   access: proxy
  #   orgId: 1
  #   url: http://loki:3100
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: true
  # - name: jaeger
  #   type: jaeger
  #   uid: my-jaeger
  #   access: browser
  #   url: http://jaeger:16686
  #   isDefault: false
  # - name: prometheus-sample
  #   access: proxy
  #   basicAuth: true
  #   basicAuthPassword: pass
  #   basicAuthUser: daco
  #   editable: false
  #   jsonData:
  #       tlsSkipVerify: true
  #   orgId: 1
  #   type: prometheus
  #   url: https://{{ printf "%s-prometheus.svc" .Release.Name }}:9090
  #   version: 1

defaultRules:
  create: false
alertmanager:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus: # https://www.infracloud.io/blogs/prometheus-operator-helm-guide/
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts: 
      - prometheus.127.0.0.1.nip.io
    paths: 
      - /
    # pathType: ImplementationSpecific