apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring
  namespace: monitoring
spec:
  dnsNames:
    - freddieentity.link
  secretName: monitoring-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer