apiVersion: v1
data:
  dex.config: |
    connectors:
    - type: ldap
      name: slapd
      id: ad
      config:
        # Ldap server address
        host: "slapd"
        insecureNoSSL: true
        insecureSkipVerify: true
        # Variable name stores ldap bindDN in argocd-secret
        bindDN: "cn=service,ou=Users,dc=acme,dc=local"
        # Variable name stores ldap bind password in argocd-secret
        bindPW: "changeit"
        usernamePrompt: Username
        # Ldap user search attributes
        userSearch:
          baseDN: "ou=users,dc=acme,dc=local"
          filter: ""
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: displayName
        # Ldap group search attributes
        groupSearch:
          baseDN: "ou=groups,dc=acme,dc=local"
          filter: "(objectClass=groupOfNames)"
          userAttr: DN
          groupAttr: member
          nameAttr: cn