kind: Pod
apiVersion: v1
metadata:
  name: newpod
spec:
  containers:
  - name: newpod
    # image: nginx:latest
    image: netcore6:dev-9cb8816
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk-pvc
