apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certificate
  namespace: monitoring
spec:
  secretName: prometheus-tls-secret
  issuerRef:
    name: homeca-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.127.0.0.1.nip.io