apiVersion: v1
kind: Secret
metadata:
  name: my-argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  # Change url, username, password with your own
  url: https://github.com/timpamungkas/devops-app-deployment
  username: timpamungkas
  password: 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