apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: docker.io/osixia/phpldapadmin:0.9.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: slapd
        - name: PHPLDAPADMIN_HTTPS
          value: 'false'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: ldap
spec:
  selector:
    app: phpldapadmin
  ports:
  - port: 80
    targetPort: 80

