apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: monitoring
  labels:
    name: prometheus-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval:     5s
      evaluation_interval: 5s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
    rule_files:
     - '/etc/rules/prom-rule.yml'
    scrape_configs:
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana:3000']
      - job_name: 'checkout-go'
        static_configs:
          - targets: ['checkoutservice:5051']
      - job_name: 'email-python'
        static_configs:
          - targets: ['emailservice:8081']
      - job_name: 'product-catalog-go'
        static_configs:
          - targets: ['productcatalogservice:3551']
      - job_name: 'recommendation-python'
        static_configs:
          - targets: ['recommendationservice:8081']
      - job_name: 'shipping-go'
        static_configs:
          - targets: ['shippingservice:50052']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-rule-conf
  labels:
    name: prom-rule-conf
data:
  prom-rule.yml: |-
    groups:
    - name: prom-rule
      rules:
      - record: job:recommendationservice_python_app_response_latency_seconds:rate1m
        expr: rate(recommendationservice_python_app_response_latency_seconds_sum[1m])
      - alert: RecommendationServiceDown
        expr: up{instance="recommendationservice:8081"} == 0
        for: 1m
        labels:
          severity: critical
      - alert: RecommendationServiceHighTraffic
        expr: job:recommendationservice_python_app_response_latency_seconds:rate1m >= 0.1
        for: 1m
        labels:
          severity: warning
      - alert: RecommendationServiceOverload
        expr: job:recommendationservice_python_app_response_latency_seconds:rate1m >= 0.25
        for: 1m
        labels:
          severity: critical