apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: "kube-prometheus-stack-operator"
  name: prometheus-operator
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      app: kube-prometheus-stack-operator
