apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-repository
  namespace: {{ .Values.destination.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.source.repoURL }}