name: Terraform Deploy

on:
  pull_request:
  push:
    branches: [main]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    # - name: Import Secrets
    #   uses: hashicorp/vault-action@v2.0.1
    #   with:
    #     url: ${{ env.VAULT_ADDR }}
    #     tlsSkipVerify: true
    #     token: ${{ secrets.VAULT_TOKEN }}
    #     secrets: |
    #       secret/data/ci app_secret

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Init
      run: terraform init -backend-config=environments/${{ env.ENV }}/${{ env.ENV }}.backend.hcl

    - name: Terraform Plan
      run: |
        terraform plan -var-file=environments/${{ env.ENV }}/${{ env.ENV }}.tfvars
